# https://www.reddit.com/r/ArgoCD/comments/15nlbs9/is_it_possible_to_create_argocd_accounts_for_the/
# https://github.com/mabusaa/argocd-course-apps-definitions/blob/main/applications%20and%20projects/project%20-%20role.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  # add an additional local user with apiKey and login capabilities
  #   apiKey - allows generating API keys
  #   login - allows to login using UI
  accounts.alice: apiKey, login
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  # add an additional local user with apiKey and login capabilities
  #   apiKey - allows generating API keys
  #   login - allows to login using UI
  accounts.bob: apiKey, login
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: mydefault
  namespace: argocd
spec:
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  
  roles:
  - name: mydefault-role
    description: Testing project roles with granular project access
    policies:
    - p, alice, applications, *, mydefault/bw-go-demo-dev, allow
    - p, alice, applications, *, mydefault/bw-go-demo-test, allow
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: go-demo
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: bw
        namespace: go-demo-dev
        url: https://kubernetes.default.svc
      - cluster: bw
        namespace: go-demo-test
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-{{namespace}}'
      namespace: argocd
    spec:
      project: mydefault
      source:
        repoURL: git@github.com:seannguyn/go-demo.git
        targetRevision: main
        path: kubernetes
      destination:
        server: '{{url}}'
        namespace: '{{namespace}}'
      syncPolicy:
         syncOptions:
          - CreateNamespace=true

