apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: go-demo
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: bw
        namespace: go-demo-dev
        url: https://kubernetes.default.svc
      - cluster: bw
        namespace: go-demo-test
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-{{namespace}}'
      namespace: argocd
    spec:
      project: mydefault
      source:
        repoURL: https://github.com/seannguyn/go-demo.git
        targetRevision: main
        path: kubernetes
      destination:
        server: '{{url}}'
        namespace: '{{namespace}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true

