apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-demo-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-demo
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: go-demo
    spec:
      containers:
      - name: go-demo
        image: go-demo:latest
        imagePullPolicy: Never
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 128Mi
---
kind: Service
apiVersion: v1
metadata:
  name:  go-demo-svc
spec:
  selector:
    app:  go-demo
  type:  ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
